name: Docker Image CI

env:
  USERNAME: remi
  OWNER: remimichel
  TAG: v0.0.1
  IMAGE_NAME: todo-api

on:
  push:
    branches: [ "main" ]

  workflow_call:
    secrets:
      CR_PAT:
        description: 'A token passed from the caller workflow'
        required: false

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        run: docker login ghcr.io -u ${{ env.USERNAME }} -p ${{ secrets.CR_PAT }}

      - name: Build Docker image
        run: docker build . --tag ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
