name: Docker Image CI

env:
  USERNAME: remi
  IMAGE_NAME: todo-api
  TAG: latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_call:
    secrets:
      CR_PAT:
        description: 'A token passed from the caller workflow'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build and publish the Docker image
      run: |
        docker login ghcr.io -u ${{ env.USERNAME }} -p ${{ secrets.CR_PAT }}
        docker build docker/ --tag ghcr.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
        docker push ghcr.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
