name: Docker Image CI

env:
  USERNAME: remi
  IMAGE_NAME: todo-api
  TAG: $(date +%s)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_call:
    secrets:
      CR_PAT:
        description: 'A token passed from the caller workflow'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and publish the Docker image
      run: |
        docker login ghcr.io -u USERNAME -p ${{ secrets.CR_PAT }}
        docker build docker/ --tag IMAGE_NAME:TAG
        docker push ghcr.io/USERNAME/IMAGE_NAME:TAG
