name: Docker Image CI

env:
  USERNAME: remi
  TAG: latest
  IMAGE_NAME: todo-api

on:
  push:
    branches: [ "main" ]

  workflow_call:
    secrets:
      CR_PAT:
        description: 'A token passed from the caller workflow'
        required: false
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        run: docker login ghcr.io -u ${{ env.USERNAME }} -p ${{ secrets.CR_PAT }}

      - name: Build Docker image
        run: docker build docker/ --tag ghcr.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Build Docker image
        run: docker push ghcr.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
